version: '3'
services:

  #
  # janus-gateway
  #
  janus-gateway:
    image: zll-rtc/janus:20231019
    container_name: janus
    #command: sh -c "nginx && /usr/local/bin/janus -F /usr/local/etc/janus"
    #network_mode: "host"
    ports:
      - "8086:8086"
      - "8088:8088"    
    volumes:
      - "./conf/janus.transport.http.jcfg:/usr/local/etc/janus/janus.transport.http.jcfg"
      - "./conf/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      - "./conf/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg"
    restart: always