name: build docker images - janus-webrtc-docker

on:
#  schedule:
#    # 定时任务 每月 1号  九点 10分
#    - cron: '10 21 1 * *'
    # 手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ssh download file
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_PORT: 22
          SOURCE: ./
          TARGET: /home/temp_janus/
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          command_timeout: 60m
          script: |
            docker ps
            cd /home/temp_janus
            sh build.sh
            #sh push.sh ${{secrets.HUB_USER}} ${{secrets.HUB_PWD}}
